## 와인 품질 데이터
- 와인 성분 변수들을 이용하여 품질을 예측하는 유명한 데이터 <br> <br>

In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import warnings
warnings.filterwarnings(action='ignore')

#### 데이터 불러오기 및 앞부분 확인

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

ModuleNotFoundError: No module named 'google'

In [4]:
data = pd.read_csv('wine.csv')
data.head()

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white

#### 데이터 shape 확인

In [9]:
data.shape

(5497, 14)

#### 컬럼명 확인

In [11]:
data.columns

Index(['index', 'quality', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'type'],
      dtype='object')

#### NaN, 데이터 타입, 개수 확인

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5497 entries, 0 to 5496
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 5497 non-null   int64
 1   quality               5497 non-null   int64
 2   fixed acidity         5497 non-null   float64
 3   volatile acidity      5497 non-null   float64
 4   citric acid           5497 non-null   float64
 5   residual sugar        5497 non-null   float64
 6   chlorides             5497 non-null   float64
 7   free sulfur dioxide   5497 non-null   float64
 8   total sulfur dioxide  5497 non-null   float64
 9   density               5497 non-null   float64
 10  pH                    5497 non-null   float64
 11  sulphates             5497 non-null   float64
 12  alcohol               5497 non-null   float64
 13  type                  5497 non-null   object
dtypes: float64(11), int64(2), object(1)
memory usage: 601.4+ KB

#### 통계값 확인

In [15]:
data.describe()

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
count,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000,5497.000000
mean,2748.000000,5.818992,7.210115,0.338163,0.318543,5.438075,0.055808,30.417682,115.566491,0.994673,3.219502,0.530524,10.504918
std,1586.991546,0.870311,1.287579,0.163224,0.145104,4.756676,0.034653,17.673881,56.288223,0.003014,0.160713,0.149396,1.194524
min,0.000000,3.000000,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.740000,0.220000,8.000000
25%,1374.000000,5.000000,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,78.000000,0.992300,3.110000,0.430000,9.500000
50%,2748.000000,6.000000,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994800,3.210000,0.510000,10.300000
75%,4122.000000,6.000000,7.700000,0.400000,0.390000,8.100000,0.064000,41.000000,155.000000,0.996930,3.320000,0.600000,11.300000
max,5496.000000,9.000000,15.900000,1.580000,1.660000,65.800000,0.610000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000

#### quality의 unique 확인

In [18]:
data.head()
data.quality.unique()

array([5, 6, 7, 8, 4, 3, 9], dtype=int64)

#### quality별로 개수 확인

In [20]:
data.quality.value_counts()

6    2416
5    1788
7     924
4     186
8     152
3      26
9       5
Name: quality, dtype: int64

#### 중요하다고 생각되는 부분만 추출

In [25]:
df=data[['quality','residual sugar','pH','alcohol','type']]
df.head(5)
df['over sugar'] = df['residual sugar'].apply(lambda x : 'normal' if x<5 else 'over') 
df.head()

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white

#### groupby를 통해 quality로 묶고 통계값(min,mean,max) 확인

In [29]:
data.groupby(['quality']).agg(["min","max","mean"])
# titanic_sample.groupby(["Pclass", "Sex"])['Fare'].mean()

        index                    fixed acidity                  \
          min   max         mean           min   max      mean
quality
3         209  5402  2847.730769           4.2  11.8  7.811538
4          29  5485  2692.709677           4.6  12.5  7.269892
5           0  5495  2762.370805           4.5  15.9  7.329195
6           3  5496  2741.139901           3.8  14.3  7.166743
7          11  5494  2794.899351           4.4  15.6  7.123972
8          25  5478  2466.427632           3.9  10.7  6.839474
9         561  3497  2354.800000           6.6   9.1  7.420000

        volatile acidity                  citric acid                  \
                     min    max      mean         min   max      mean
quality
3                   0.17  1.580  0.538077        0.00  0.66  0.266923
4                   0.11  1.130  0.447285        0.00  1.00  0.280323
5                   0.10  1.330  0.387855        0.00  1.00  0.308043
6                   0.08  1.040  0.312301        0.00  1.66  0.323411
7                   0.08  0.915  0.289724        0.00  0.76  0.332987
8                   0.12  0.850  0.292730        0.03  0.74  0.330263
9                   0.24  0.360  0.298000        0.29  0.49  0.386000

        residual sugar                  chlorides                   \
                   min    max      mean       min    max      mean
quality
3                 1.15  16.20  5.203846     0.022  0.267  0.076500
4                 0.70  15.40  4.145430     0.013  0.610  0.059247
5                 0.60  23.50  5.792422     0.009  0.464  0.064417
6                 0.70  65.80  5.535141     0.015  0.415  0.053932
7                 0.90  19.25  4.748918     0.012  0.358  0.045352
8                 0.80  14.80  5.581579     0.014  0.121  0.041105
9                 1.60  10.60  4.120000     0.018  0.035  0.027400

        free sulfur dioxide                   total sulfur dioxide         \
                        min    max       mean                  min    max
quality
3                       3.0  289.0  40.096154                  9.0  440.0
4                       3.0  138.5  20.553763                  7.0  272.0
5                       2.0  131.0  30.174217                  6.0  344.0
6                       1.0  112.0  30.969578                  6.0  294.0
7                       3.0  108.0  30.457251                  7.0  229.0
8                       3.0  105.0  34.585526                 12.0  212.5
9                      24.0   57.0  33.400000                 85.0  139.0

                     density                       pH                  \
               mean      min      max      mean   min   max      mean
quality
3        121.461538  0.99110  1.00080  0.995713  2.87  3.63  3.250385
4        104.811828  0.98920  1.00040  0.994730  2.74  3.90  3.228602
5        120.370805  0.98722  1.00315  0.995843  2.79  3.79  3.213384
6        115.357616  0.98758  1.03898  0.994527  2.74  4.01  3.219611
7        108.178571  0.98711  1.00320  0.993122  2.84  3.82  3.228333
8        119.421053  0.98713  1.00060  0.992544  2.94  3.57  3.216711
9        116.000000  0.98965  0.99700  0.991460  3.20  3.41  3.308000

        sulphates                 alcohol
              min   max      mean     min   max       mean
quality
3            0.28  0.74  0.500000     8.0  12.6  10.251923
4            0.25  2.00  0.500484     8.6  13.5  10.180376
5            0.27  1.98  0.525017     8.0  14.9   9.846875
6            0.25  1.95  0.532686     8.4  14.0  10.606015
7            0.22  1.36  0.546786     8.6  14.2  11.383864
8            0.25  1.10  0.506184     8.8  14.0  11.680921
9            0.36  0.61  0.466000    10.4  12.9  12.180000

#### groupby를 통해 quality/type로 묶고 개수 세기

In [30]:
data.groupby(['quality','type']).size()

quality  type
3        red         9
         white      17
4        red        41
         white     145
5        red       571
         white    1217
6        red       535
         white    1881
7        red       169
         white     755
8        red        13
         white     139
9        white       5
dtype: int64

#### 알코올 함량을 기준으로 오름차순 정리 (20개)

In [33]:
data.head()
data.sort_values("alcohol").head(20)

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
4254,4254,3,4.2,0.215,0.23,5.10,0.041,64.0,157.0,0.99688,3.42,0.44,8.0,white
5077,5077,5,4.5,0.190,0.21,0.95,0.033,89.0,159.0,0.99332,3.34,0.42,8.0,white
1768,1768,3,10.4,0.610,0.49,2.10,0.200,5.0,16.0,0.99940,3.16,0.63,8.4,red
4176,4176,5,6.2,0.310,0.23,3.30,0.052,34.0,113.0,0.99429,3.16,0.48,8.4,white
479,479,6,14.3,0.310,0.74,1.80,0.075,6.0,15.0,1.00080,2.86,0.79,8.4,red
3725,3725,5,7.6,0.280,0.49,20.15,0.060,30.0,145.0,1.00196,3.01,0.44,8.5,white
3772,3772,6,6.4,0.180,0.48,18.00,0.054,56.0,183.0,1.00038,2.98,0.61,8.5,white
172,172,6,6.5,0.180,0.48,18.00,0.054,56.0,183.0,1.00038,2.98,0.61,8.5,white
255,255,5,10.0,0.380,0.38,1.60,0.169,27.0,90.0,0.99914,3.15,0.65,8.5,red
3062,3062,5,6.1,0.430,0.35,9.10,0.059,83.0,249.0,0.99710,3.37,0.50,8.5,white
2377,2377,5,6.5,0.360,0.16,1.30,0.054,11.0,107.0,0.99398,3.19,0.39,8.5,white
1427,1427,6,6.3,0.200,0.30,5.90,0.034,35.0,152.0,0.99642,3.47,0.40,8.5,white
4249,4249,4,7.2,0.400,0.62,10.80,0.041,70.0,189.0,0.99760,3.08,0.49,8.6,white
3155,3155,4,6.5,0.270,0.19,4.20,0.046,6.0,114.0,0.99550,3.25,0.35,8.6,white
4224,4224,6,6.8,0.220,0.24,4.90,0.092,30.0,123.0,0.99510,3.03,0.46,8.6,white
3046,3046,5,7.3,0.310,0.69,10.20,0.041,58.0,160.0,0.99770,3.06,0.45,8.6,white
3640,3640,7,8.0,0.220,0.42,14.60,0.044,45.0,163.0,1.00030,3.21,0.69,8.6,white
30,30,5,6.8,0.440,0.20,16.00,0.065,61.0,186.0,0.99884,3.13,0.45,8.6,white
3656,3656,5,6.9,0.270,0.49,23.50,0.057,59.0,235.0,1.00240,2.98,0.47,8.6,white
3355,3355,4,7.3,0.360,0.54,13.30,0.054,63.0,193.0,0.99864,3.06,0.49,8.6,white

#### 알코올 함량을 기준으로 내림차순 정리 (20개)

In [35]:
data.head()
data.sort_values("alcohol", ascending=False).head(20)

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
2787,2787,5,15.9,0.360,0.65,7.5,0.096,22.0,71.0,0.99760,2.98,0.84,14.90,red
5340,5340,7,6.4,0.350,0.28,1.6,0.037,31.0,113.0,0.98779,3.12,0.40,14.20,white
4964,4964,7,5.8,0.610,0.01,8.4,0.041,31.0,104.0,0.99090,3.26,0.72,14.05,white
4059,4059,6,5.2,0.340,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.00,red
3005,3005,7,5.0,0.455,0.18,1.9,0.036,33.0,106.0,0.98746,3.21,0.83,14.00,white
4150,4150,7,5.8,0.290,0.21,2.6,0.025,12.0,120.0,0.98940,3.39,0.79,14.00,white
1963,1963,6,8.8,0.460,0.45,2.6,0.065,7.0,18.0,0.99470,3.32,0.79,14.00,red
984,984,8,4.9,0.330,0.31,1.2,0.016,39.0,150.0,0.98713,3.33,0.59,14.00,white
876,876,7,4.9,0.420,0.00,2.1,0.048,16.0,42.0,0.99154,3.71,0.74,14.00,red
2142,2142,6,5.2,0.340,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.00,red
3848,3848,8,5.5,0.490,0.03,1.8,0.044,28.0,87.0,0.99080,3.50,0.82,14.00,red
5160,5160,6,5.8,0.390,0.47,7.5,0.027,12.0,88.0,0.99070,3.38,0.45,14.00,white
3265,3265,7,4.7,0.455,0.18,1.9,0.036,33.0,106.0,0.98746,3.21,0.83,14.00,white
5448,5448,7,5.8,0.240,0.28,1.4,0.038,40.0,76.0,0.98711,3.10,0.29,13.90,white
4492,4492,7,5.8,0.320,0.20,2.6,0.027,17.0,123.0,0.98936,3.36,0.78,13.90,white
1463,1463,7,5.9,0.340,0.22,2.4,0.030,19.0,135.0,0.98940,3.41,0.78,13.90,white
196,196,6,4.7,0.785,0.00,3.4,0.036,23.0,134.0,0.98981,3.53,0.92,13.80,white
2587,2587,6,5.4,0.270,0.22,4.6,0.022,29.0,107.0,0.98889,3.33,0.54,13.80,white
3342,3342,7,5.6,0.490,0.13,4.5,0.039,17.0,116.0,0.99070,3.42,0.90,13.70,white
5456,5456,7,5.9,0.170,0.29,3.1,0.030,32.0,123.0,0.98913,3.41,0.33,13.70,white

#### quailty가 7 이상인 데이터 추출 (20개)

In [38]:
data.head()
data[data.quality>7].head(20)

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
25,25,8,6.6,0.29,0.31,3.90,0.027,39.0,96.0,0.99035,3.24,0.60,12.6,white
54,54,8,7.0,0.53,0.43,6.10,0.029,6.0,76.0,0.99118,3.08,0.50,12.5,white
71,71,8,6.8,0.19,0.32,7.05,0.019,54.0,188.0,0.99350,3.25,0.37,11.1,white
122,122,8,6.8,0.24,0.29,2.00,0.044,15.0,96.0,0.99232,3.23,0.64,10.4,white
165,165,8,6.5,0.44,0.47,5.45,0.014,44.0,137.0,0.98984,3.13,0.32,13.0,white
168,168,8,5.4,0.53,0.16,2.70,0.036,34.0,128.0,0.98856,3.20,0.53,13.2,white
208,208,8,5.8,0.17,0.34,1.80,0.045,96.0,170.0,0.99035,3.38,0.90,11.8,white
228,228,8,5.2,0.30,0.34,1.50,0.038,18.0,96.0,0.98942,3.56,0.48,13.0,white
270,270,8,8.0,0.13,0.25,1.10,0.033,15.0,86.0,0.99044,2.98,0.39,11.2,white
327,327,8,6.5,0.30,0.27,4.00,0.038,37.0,97.0,0.99026,3.20,0.60,12.6,white
341,341,8,7.9,0.28,0.41,2.00,0.044,50.0,152.0,0.99340,3.45,0.49,10.7,white
360,360,8,7.6,0.20,0.30,14.20,0.056,53.0,212.5,0.99900,3.14,0.46,8.9,white
362,362,8,7.0,0.12,0.29,10.30,0.039,41.0,98.0,0.99564,3.19,0.38,9.8,white
363,363,8,6.7,0.24,0.30,3.85,0.042,105.0,179.0,0.99189,3.04,0.59,11.3,white
435,435,8,7.0,0.36,0.32,10.05,0.045,37.0,131.0,0.99352,3.09,0.33,11.7,white
442,442,8,7.0,0.36,0.32,10.05,0.045,37.0,131.0,0.99352,3.09,0.33,11.7,white
465,465,8,8.0,0.44,0.49,9.10,0.031,46.0,151.0,0.99260,3.16,0.27,12.7,white
491,491,8,7.6,0.20,0.30,14.20,0.056,53.0,212.5,0.99900,3.14,0.46,8.9,white
513,513,8,6.6,0.33,0.31,1.30,0.020,29.0,89.0,0.99035,3.26,0.44,12.4,white
530,530,8,7.3,0.25,0.36,2.10,0.034,30.0,177.0,0.99085,3.25,0.40,11.9,white

#### alcohol을 기준으로 10도가 넘으면 'strong' 아니면 'weak'으로 표시 (lambda 쓰세요)

In [47]:
data['temp'] = data['alcohol'].apply(lambda x: 'string' if x>10 else 'weak')
data.head()

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type,temp
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white,string
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red,weak
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white,string
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white,string
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white,string

#### merge 실습을 위해 데이터를 인위적으로 나눠볼게요

In [50]:
df_x = data[['quality', 'fixed acidity', 'citric acid']]

In [51]:
df_y = data[['quality', 'volatile acidity', 'chlorides', 'alcohol']]

#### quality를 기준으로 inner join

In [53]:
result = pd.merge(df_x,df_y,how='inner',on='quality')
result.head()

   quality  fixed acidity  citric acid  volatile acidity  chlorides  alcohol
0        5            5.6         0.06             0.695      0.042     10.2
1        5            5.6         0.06             0.610      0.067      9.5
2        5            5.6         0.06             0.210      0.057     10.9
3        5            5.6         0.06             0.220      0.051      9.6
4        5            5.6         0.06             0.240      0.046      8.7

#### quality를 기준으로 outer join

In [54]:
result_ = pd.merge(df_x,df_y, how='outer',on='quality')
result_.head()

   quality  fixed acidity  citric acid  volatile acidity  chlorides  alcohol
0        5            5.6         0.06             0.695      0.042     10.2
1        5            5.6         0.06             0.610      0.067      9.5
2        5            5.6         0.06             0.210      0.057     10.9
3        5            5.6         0.06             0.220      0.051      9.6
4        5            5.6         0.06             0.240      0.046      8.7

<br>수고하셨습니다! 넘파이와 판다스는 기능이 정말 많아서 이번 세션에서 다 다루진 못했습니다..! <br>
하지만 우리에겐 구글이 있죠 😎 <br>
무수한 블로그와 스택오버플로우를 뒤지다 보면 필요한 기능을 찾으실 수 있습니다<br>
직접 데이터를 만져보면서 여러 함수들을 써보면 저절로 넘파이와 판다스가 손에 익으실 거에요! :)<br>